name: mit
recipe: drupal9
config:
  php: '8.1'
  via: apache:4
  webroot: .
  xdebug: true
  drupal: true
services:
  pma:
    type: phpmyadmin
    hosts:
      - mitproject.com
    proxy:
      appserver:
        - mitproject.com
proxy:
  pma:
    - phpmyadmin.lndo.site
  mitproject.com:
    appserver
tooling:
  drupal:
    service: appserver
# hosts:
#     - mitproject.com




